#!/usr/bin/env bash

develop_branch="develop"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

[ "$current_branch" != "$develop_branch" ] && exit 0

commit_regex='(US[0-9]+|merge|CPE-[0-9]+)'

error_msg="Aborting commit. Your commit message is missing either a US#/JIRA Issue('US')"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
